name: todo_app
description: A new Flutter project for managing tasks.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2
  provider: ^6.0.0
  flutter_local_notifications: ^17.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true